name: ecr-docker-password
author: Ahton89
description: Small action to get the docker password for ECR
inputs:
  ecr_aws_access_key_id:
      description: 'AWS Access Key ID'
      required: true
  ecr_aws_secret_access_key:
      description: 'AWS Secret Access Key'
      required: true
  ecr_aws_region:
      description: 'AWS Region'
      required: false
outputs:
  ecr-docker-password:
    description: 'Docker password for ECR'
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.ecr_aws_access_key_id }}
    - ${{ inputs.ecr_aws_secret_access_key }}
    - ${{ inputs.ecr_aws_region }}