name: ecr-docker-password
author: Ahton89
description: Small action to get the docker password for ECR
inputs:
  access_key_id:
      description: 'AWS Access Key ID'
      required: true
  secret_access_key:
      description: 'AWS Secret Access Key'
      required: true
  region:
      description: 'AWS Region'
      required: false
outputs:
  ecr-docker-password:
    description: 'Docker password for ECR'
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.access_key_id }}
    - ${{ inputs.secret_access_key }}
    - ${{ inputs.region }}